routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\SmtestController;

Route::get('/', function () {
    return view('welcome');
});
Route::resource('smtest','SmtestController');

app/Smtest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Smtest extends Model
{
    protected $guarded=[];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SmtestController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SmtestForm;
use App\Smtest;
use Illuminate\Http\Request;

class SmtestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $smtest=Smtest::all();
        return view('smtest.index',compact('smtest'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('smtest.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SmtestForm  $request)
    {
        Smtest::create($request->all());
        return redirect('smtest');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Smtest  $smtest
     * @return \Illuminate\Http\Response
     */
    public function show(Smtest $smtest)
    {
        return view('smtest.show',compact('smtest'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Smtest  $smtest
     * @return \Illuminate\Http\Response
     */
    public function edit(Smtest $smtest)
    {
        return view('smtest.edit',compact('smtest'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Smtest  $smtest
     * @return \Illuminate\Http\Response
     */
    public function update( Smtest $smtest , SmtestForm $request)
    {
        $smtest->update($request->all());
        return redirect('smtest');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Smtest  $smtest
     * @return \Illuminate\Http\Response
     */
    public function destroy(Smtest $smtest)
    {
        $smtest->delete();
        return redirect('smtest/create');
    }
}

resources/views/layout/footer.blade.php
<footer class="bg-black small text-center text-white-50">
    <div class="container">
        Copyright &copy; Your Website 2018
    </div>
</footer>

resources/views/layout/head.blade.php
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>laravel test</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{asset('css/grayscale.min.css')}}" rel="stylesheet">

</head>

resources/views/layout/header.blade.php
{{--<header class="masthead">
    <div class="container d-flex h-100 align-items-center">
        <h1 style="text-align: center" >FOOD APP</h1>
    </div>
</header>--}}

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
@include('layout.head')
<body id="page-top">
@include('layout.header')
@include('layout.nav')
@yield('content')
@include('layout.footer')
@include('layout.script')
</body>
</html>

resources/views/layout/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Laravel test</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{url('#create')}}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#projects">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#signup">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layout/script.blade.php
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Plugin JavaScript -->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for this template -->
<script src="{{asset('js/grayscale.min.js')}}"></script>

resources/views/smtest/create.blade.php
@extends('layout.master')
@section('content')
<form method="post" action="{{route('smtest.create')}}">
    @include('smtest.form',
    ['smtest'=>new App\smtest,])
</form>
@endsection

resources/views/smtest/edit.blade.php
@extends('layout.master')
@section('content')
    <form method="post" action="{{route('smtest.update',['testcase'=>$testcase->id])}}">
        @include('smtest.form',
        ['smtest'=>new App\smtest,])
    </form>
@endsection

resources/views/smtest/form.blade.php
@csrf
<div class="container">
<div class="form-group">
        <label for="formGroupExampleInput">title</label>
        <input type="text" name="title" class="form-control" id="formGroupExampleInput" placeholder="Example input" value="{{old('title')??$smtest->title}}">
    </div>
    <div class="form-group">
        <label for="sel1">Quantity :</label>
        <input type="number" name="quantity" class="form-control" id="formGroupExampleInput" placeholder="Example input" value="{{old('quantity')??$smtest->quantity}}">

    </div>
    <div class="form-group">
        <label for="formGroupExampleInput">buy</label>
        <input type="text" name="buy" class="form-control" id="formGroupExampleInput" placeholder="Example input" value="{{old('buy')??$smtest->buy}}">
    <button>
        {{$SubmitButtonText??'Create New task'}}
    </button>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/smtest/index.blade.php
<ol>
@foreach
<li>{{$smtest->title}}</li>
<li>{{$smtest->quantity}}</li>
        <li>{{$smtest->buy}}</li>
    @endforeach
</ol>

resources/views/smtest/show.blade.php
<ul>
    <li><a href="{{route('smtest.edit',['smtest'=>$smtest->id])}}">
            {{$testCase->id}}</a><br>
        {{$smtest->title}}<br>
        {{$smtest->quantity}}<br>
        {{$smtest->buy}}<br>

</ul>
<form method="post" action="/smtest/{{$smtsest->id}}">
    @csrf
    @method('DELETE')
    <button type="submit">delete</button>